var annotated_dup =
[
    [ "editeurpanovisu", "namespaceediteurpanovisu.html", [
      [ "gpu", "namespaceediteurpanovisu_1_1gpu.html", [
        [ "GPUKernelLoader", "classediteurpanovisu_1_1gpu_1_1GPUKernelLoader.html", "classediteurpanovisu_1_1gpu_1_1GPUKernelLoader" ],
        [ "GPUManager", "classediteurpanovisu_1_1gpu_1_1GPUManager.html", "classediteurpanovisu_1_1gpu_1_1GPUManager" ],
        [ "ImageResizeGPU", "classediteurpanovisu_1_1gpu_1_1ImageResizeGPU.html", "classediteurpanovisu_1_1gpu_1_1ImageResizeGPU" ],
        [ "InterpolationMethod", "enumediteurpanovisu_1_1gpu_1_1InterpolationMethod.html", "enumediteurpanovisu_1_1gpu_1_1InterpolationMethod" ],
        [ "TestBicubicVsLanczos", "classediteurpanovisu_1_1gpu_1_1TestBicubicVsLanczos.html", "classediteurpanovisu_1_1gpu_1_1TestBicubicVsLanczos" ],
        [ "TestImageResize", "classediteurpanovisu_1_1gpu_1_1TestImageResize.html", "classediteurpanovisu_1_1gpu_1_1TestImageResize" ],
        [ "TestImageResizeInteractive", "classediteurpanovisu_1_1gpu_1_1TestImageResizeInteractive.html", "classediteurpanovisu_1_1gpu_1_1TestImageResizeInteractive" ],
        [ "TestReductionImage", "classediteurpanovisu_1_1gpu_1_1TestReductionImage.html", "classediteurpanovisu_1_1gpu_1_1TestReductionImage" ]
      ] ],
      [ "util", "namespaceediteurpanovisu_1_1util.html", [
        [ "LocalHTTPServer", "classediteurpanovisu_1_1util_1_1LocalHTTPServer.html", "classediteurpanovisu_1_1util_1_1LocalHTTPServer" ],
        [ "SvgIconLoader", "classediteurpanovisu_1_1util_1_1SvgIconLoader.html", "classediteurpanovisu_1_1util_1_1SvgIconLoader" ]
      ] ],
      [ "AideDialogController", "classediteurpanovisu_1_1AideDialogController.html", "classediteurpanovisu_1_1AideDialogController" ],
      [ "ApiKeysConfig", "classediteurpanovisu_1_1ApiKeysConfig.html", "classediteurpanovisu_1_1ApiKeysConfig" ],
      [ "BigDecimalField", "classediteurpanovisu_1_1BigDecimalField.html", "classediteurpanovisu_1_1BigDecimalField" ],
      [ "BuildNumberIncrementer", "classediteurpanovisu_1_1BuildNumberIncrementer.html", "classediteurpanovisu_1_1BuildNumberIncrementer" ],
      [ "CartePanoVisu", "classediteurpanovisu_1_1CartePanoVisu.html", "classediteurpanovisu_1_1CartePanoVisu" ],
      [ "ConfigDialogController", "classediteurpanovisu_1_1ConfigDialogController.html", "classediteurpanovisu_1_1ConfigDialogController" ],
      [ "ConversionRatio2to1DialogController", "classediteurpanovisu_1_1ConversionRatio2to1DialogController.html", "classediteurpanovisu_1_1ConversionRatio2to1DialogController" ],
      [ "CoordonneesGeographiques", "classediteurpanovisu_1_1CoordonneesGeographiques.html", "classediteurpanovisu_1_1CoordonneesGeographiques" ],
      [ "Diaporama", "classediteurpanovisu_1_1Diaporama.html", "classediteurpanovisu_1_1Diaporama" ],
      [ "DocumentationDialog", "classediteurpanovisu_1_1DocumentationDialog.html", "classediteurpanovisu_1_1DocumentationDialog" ],
      [ "EditeurHTML", "classediteurpanovisu_1_1EditeurHTML.html", "classediteurpanovisu_1_1EditeurHTML" ],
      [ "EditeurPanovisu", "classediteurpanovisu_1_1EditeurPanovisu.html", "classediteurpanovisu_1_1EditeurPanovisu" ],
      [ "EquiCubeDialogController", "classediteurpanovisu_1_1EquiCubeDialogController.html", "classediteurpanovisu_1_1EquiCubeDialogController" ],
      [ "EsriTileRetriever", "classediteurpanovisu_1_1EsriTileRetriever.html", "classediteurpanovisu_1_1EsriTileRetriever" ],
      [ "ExtensionsFilter", "classediteurpanovisu_1_1ExtensionsFilter.html", "classediteurpanovisu_1_1ExtensionsFilter" ],
      [ "GestionnaireDiaporamaController", "classediteurpanovisu_1_1GestionnaireDiaporamaController.html", "classediteurpanovisu_1_1GestionnaireDiaporamaController" ],
      [ "GestionnaireInterfaceController", "classediteurpanovisu_1_1GestionnaireInterfaceController.html", "classediteurpanovisu_1_1GestionnaireInterfaceController" ],
      [ "GestionnairePlanController", "classediteurpanovisu_1_1GestionnairePlanController.html", "classediteurpanovisu_1_1GestionnairePlanController" ],
      [ "HotSpot", "classediteurpanovisu_1_1HotSpot.html", "classediteurpanovisu_1_1HotSpot" ],
      [ "HotspotDiaporama", "classediteurpanovisu_1_1HotspotDiaporama.html", "classediteurpanovisu_1_1HotspotDiaporama" ],
      [ "HotspotHTML", "classediteurpanovisu_1_1HotspotHTML.html", "classediteurpanovisu_1_1HotspotHTML" ],
      [ "HotspotImage", "classediteurpanovisu_1_1HotspotImage.html", "classediteurpanovisu_1_1HotspotImage" ],
      [ "HuggingFaceClient", "classediteurpanovisu_1_1HuggingFaceClient.html", "classediteurpanovisu_1_1HuggingFaceClient" ],
      [ "ImageEditeurHTML", "classediteurpanovisu_1_1ImageEditeurHTML.html", "classediteurpanovisu_1_1ImageEditeurHTML" ],
      [ "ImageFond", "classediteurpanovisu_1_1ImageFond.html", "classediteurpanovisu_1_1ImageFond" ],
      [ "Launcher", "classediteurpanovisu_1_1Launcher.html", "classediteurpanovisu_1_1Launcher" ],
      [ "ListePanoramiqueCellule", "classediteurpanovisu_1_1ListePanoramiqueCellule.html", "classediteurpanovisu_1_1ListePanoramiqueCellule" ],
      [ "MapMarkerWithHtml", "classediteurpanovisu_1_1MapMarkerWithHtml.html", "classediteurpanovisu_1_1MapMarkerWithHtml" ],
      [ "MarkdownViewer", "classediteurpanovisu_1_1MarkdownViewer.html", "classediteurpanovisu_1_1MarkdownViewer" ],
      [ "MarqueurGeolocalisation", "classediteurpanovisu_1_1MarqueurGeolocalisation.html", "classediteurpanovisu_1_1MarqueurGeolocalisation" ],
      [ "NavigateurCarte", "classediteurpanovisu_1_1NavigateurCarte.html", "classediteurpanovisu_1_1NavigateurCarte" ],
      [ "NavigateurCarteGluon", "classediteurpanovisu_1_1NavigateurCarteGluon.html", "classediteurpanovisu_1_1NavigateurCarteGluon" ],
      [ "NavigateurCarteSeul", "classediteurpanovisu_1_1NavigateurCarteSeul.html", "classediteurpanovisu_1_1NavigateurCarteSeul" ],
      [ "NavigateurOpenLayers", "classediteurpanovisu_1_1NavigateurOpenLayers.html", "classediteurpanovisu_1_1NavigateurOpenLayers" ],
      [ "NavigateurOpenLayersSeul", "classediteurpanovisu_1_1NavigateurOpenLayersSeul.html", "classediteurpanovisu_1_1NavigateurOpenLayersSeul" ],
      [ "NavigateurPanoramique", "classediteurpanovisu_1_1NavigateurPanoramique.html", "classediteurpanovisu_1_1NavigateurPanoramique" ],
      [ "OllamaService", "classediteurpanovisu_1_1OllamaService.html", "classediteurpanovisu_1_1OllamaService" ],
      [ "OpenRouterClient", "classediteurpanovisu_1_1OpenRouterClient.html", "classediteurpanovisu_1_1OpenRouterClient" ],
      [ "OrdrePanoramique", "classediteurpanovisu_1_1OrdrePanoramique.html", "classediteurpanovisu_1_1OrdrePanoramique" ],
      [ "PaneOutil", "classediteurpanovisu_1_1PaneOutil.html", "classediteurpanovisu_1_1PaneOutil" ],
      [ "PanoramicCube", "classediteurpanovisu_1_1PanoramicCube.html", "classediteurpanovisu_1_1PanoramicCube" ],
      [ "Panoramique", "classediteurpanovisu_1_1Panoramique.html", "classediteurpanovisu_1_1Panoramique" ],
      [ "PanoramiqueCellule", "classediteurpanovisu_1_1PanoramiqueCellule.html", "classediteurpanovisu_1_1PanoramiqueCellule" ],
      [ "Plan", "classediteurpanovisu_1_1Plan.html", "classediteurpanovisu_1_1Plan" ],
      [ "PopUpDialogController", "classediteurpanovisu_1_1PopUpDialogController.html", "classediteurpanovisu_1_1PopUpDialogController" ],
      [ "PrevisualiserConversionDialog", "classediteurpanovisu_1_1PrevisualiserConversionDialog.html", "classediteurpanovisu_1_1PrevisualiserConversionDialog" ],
      [ "ReadWriteImage", "classediteurpanovisu_1_1ReadWriteImage.html", "classediteurpanovisu_1_1ReadWriteImage" ],
      [ "RedimensionnementImagesDialogController", "classediteurpanovisu_1_1RedimensionnementImagesDialogController.html", "classediteurpanovisu_1_1RedimensionnementImagesDialogController" ],
      [ "TestAIClients", "classediteurpanovisu_1_1TestAIClients.html", "classediteurpanovisu_1_1TestAIClients" ],
      [ "TextUtils", "classediteurpanovisu_1_1TextUtils.html", "classediteurpanovisu_1_1TextUtils" ],
      [ "ThemeManager", "classediteurpanovisu_1_1ThemeManager.html", "classediteurpanovisu_1_1ThemeManager" ],
      [ "TransformationsPanoramique", "classediteurpanovisu_1_1TransformationsPanoramique.html", "classediteurpanovisu_1_1TransformationsPanoramique" ],
      [ "TransformationsPanoramiqueGPU", "classediteurpanovisu_1_1TransformationsPanoramiqueGPU.html", "classediteurpanovisu_1_1TransformationsPanoramiqueGPU" ],
      [ "VisualiseurImagesPanoramiques", "classediteurpanovisu_1_1VisualiseurImagesPanoramiques.html", "classediteurpanovisu_1_1VisualiseurImagesPanoramiques" ],
      [ "ZoneTelecommande", "classediteurpanovisu_1_1ZoneTelecommande.html", "classediteurpanovisu_1_1ZoneTelecommande" ]
    ] ]
];