#!/bin/bash

# Script Bash pour incrémenter le numéro de build
# Exécuté automatiquement par Maven avant la compilation

set -e

echo "=== Incrémentation du numéro de build ==="

# Fichiers à mettre à jour
BUILD_NUM_FILE="build.num"
I18N_FILE="src/editeurpanovisu/i18n/PanoVisu.properties"
PROJECT_FILE="src/project.properties"
POM_FILE="pom.xml"

# Fonction pour lire le numéro de build
get_build_number() {
    if [ ! -f "$BUILD_NUM_FILE" ]; then
        echo "Fichier build.num non trouvé, création avec build=1990"
        echo 1990
        return
    fi
    
    local current_build
    current_build=$(grep "^build\.number=" "$BUILD_NUM_FILE" | cut -d'=' -f2 | tr -d '\r\n ')
    
    if [ -z "$current_build" ] || ! [[ "$current_build" =~ ^[0-9]+$ ]]; then
        echo 1990
        return
    fi
    
    echo "$current_build"
}

# Fonction pour incrémenter et sauvegarder le numéro de build
increment_build_number() {
    local current_build
    current_build=$(get_build_number)
    local new_build=$((current_build + 1))
    
    echo "Build actuel: $current_build"
    echo "Nouveau build: $new_build"
    
    # Mettre à jour build.num
    echo "build.number=$new_build" > "$BUILD_NUM_FILE"
    echo "# Build number - Auto-generated by Maven" >> "$BUILD_NUM_FILE"
    echo "# Last updated: $(date)" >> "$BUILD_NUM_FILE"
    
    echo "$new_build"
}

# Fonction pour mettre à jour les fichiers
update_files() {
    local build_number=$1
    
    # Mettre à jour le fichier i18n si il existe
    if [ -f "$I18N_FILE" ]; then
        if grep -q "build=" "$I18N_FILE"; then
            sed -i "s/build=.*/build=$build_number/" "$I18N_FILE"
            echo "✓ Fichier i18n mis à jour: $I18N_FILE"
        fi
    fi
    
    # Mettre à jour project.properties si il existe
    if [ -f "$PROJECT_FILE" ]; then
        if grep -q "build=" "$PROJECT_FILE"; then
            sed -i "s/build=.*/build=$build_number/" "$PROJECT_FILE"
            echo "✓ Fichier project mis à jour: $PROJECT_FILE"
        fi
    fi
    
    echo "✓ Build $build_number enregistré dans $BUILD_NUM_FILE"
}

# Script principal
main() {
    echo "Répertoire de travail: $(pwd)"
    
    # Incrémenter le build
    local new_build
    new_build=$(increment_build_number)
    
    # Mettre à jour les fichiers
    update_files "$new_build"
    
    echo "=== Incrémentation terminée avec succès ==="
    echo "Nouveau numéro de build: $new_build"
}

# Exécuter le script principal
main "$@"