function estTactile(){return!!("ontouchstart"in window)}
function panovisu(a){function Zc(){this.type="panoramique";this.lat=this.long=0;this.image=this.contenu="";this.anime="false";this.info=""}function $c(){this.txt=this.xml=this.image=""}function ad(){this.positY=this.positX=0;this.texte=this.xml=""}function bd(){this.posY=this.posX=this.infobulle=this.url=this.fichier="";this.offsetY=this.offsetX=0;this.opacite=1;this.tailleY=this.tailleX="";this.masquable=!0}function Jc(a){ra=sa=0;id1=a.split("-");a=id1[0];switch(a){case "xmoins":sa-=.5;break;case "xplus":sa+=
.5;break;case "ymoins":ra+=.5;break;case "yplus":ra-=.5}}function Kc(){if(Na){"oui"===Oa&&$("#barre-"+a).fadeOut(500);"oui"===Pa&&$("#boussole-"+a).fadeOut(500);"oui"===Qa&&$("#info-"+a).fadeOut(500);"oui"===Ra&&($("#plan-"+a).fadeOut(500),$("#planTitre-"+a).fadeOut(500));"oui"===Sa&&$("#reseauxSociaux-"+a).fadeOut(500);"oui"===Ta&&($("#titreVignettes-"+a).fadeOut(500),$("#divVignettes-"+a).fadeOut(500),"left"===r&&$("#divPrecedent-"+a).css({left:0}),"right"===r&&$("#divSuivant-"+a).css({right:0}));
for(d=0;d<w;d++)h[d].masquable&&$("#imageFond-"+d+"-"+a).fadeOut(500);Na=!1}else{"oui"===Oa&&$("#barre-"+a).fadeIn(500);"oui"===Pa&&$("#boussole-"+a).fadeIn(500);"oui"===Qa&&"oui"===Aa&&$("#info-"+a).fadeIn(500);"oui"===Ra&&($("#plan-"+a).fadeIn(500),$("#planTitre-"+a).fadeIn(500));"oui"===Sa&&$("#reseauxSociaux-"+a).fadeIn(500);if("oui"===Ta)if($("#titreVignettes-"+a).fadeIn(500),$("#divVignettes-"+a).fadeIn(500),H)"left"===r&&$("#divPrecedent-"+a).css({left:0}),"right"===r&&$("#divSuivant-"+a).css({right:0});
else{var c=$("#divVignettes-"+a).width()+6;"left"===r&&$("#divPrecedent-"+a).css({left:c});"right"===r&&$("#divSuivant-"+a).css({right:c})}for(d=0;d<w;d++)h[d].masquable&&$("#imageFond-"+d+"-"+a).fadeIn(500);Na=!0}}function kc(){ba?($("#planTitre-"+a).css({transform:"translateX(-"+parseInt($("#planImg-"+a).width()+20)+"px) rotate(90deg)"}),$("#plan-"+a).css({transform:"translateX(-"+parseInt($("#planImg-"+a).width()+20)+"px)"})):($("#planTitre-"+a).css({transform:"translateX(0px)  rotate(90deg)"}),
$("#plan-"+a).css({transform:"translateX(0px)"}))}function lc(){ba?($("#planTitre-"+a).css({transform:"translateX("+parseInt($("#planImg-"+a).width()+20)+"px)  rotate(90deg)"}),$("#plan-"+a).css({transform:"translateX("+parseInt($("#planImg-"+a).width()+20)+"px)"})):($("#planTitre-"+a).css({transform:"translateX(0px)  rotate(90deg)"}),$("#plan-"+a).css({transform:"translateX(0px)"}))}function mc(){var c=e+5;if(H)switch(r){case "left":$("#divVignettes-"+a).css({transform:"translateX(-"+($("#divVignettes-"+
a).width()+5)+"px)"});$("#titreVignettes-"+a).css({transform:"translateX(-"+($("#divVignettes-"+a).width()+5)+"px) rotate(90deg)"});dX1=parseInt(J);$("#divPrecedent-"+a).css("left","0");"left"===C&&("top"===K?$("#barre-"+a).css({left:dX1+$("#titreVignettes-"+a).height()+4+"px"}):$("#barre-"+a).css({left:dX1+"px"}));L&&"left"===t&&("top"===x?$("#boussole-"+a).css(t,parseInt(y)+$("#titreVignettes-"+a).height()+4+"px"):$("#boussole-"+a).css(t,parseInt(y)+"px"));break;case "right":$("#divVignettes-"+
a).css({transform:"translateX("+($("#divVignettes-"+a).width()+5)+"px)"});$("#titreVignettes-"+a).css({transform:"translateX("+($("#divVignettes-"+a).width()+5)+"px) rotate(90deg)"});dX1=parseInt(J);$("#divSuivant-"+a).css("right","0");"right"===C&&("top"===K?$("#barre-"+a).css({right:dX1+$("#titreVignettes-"+a).height()+4+"px"}):$("#barre-"+a).css({right:dX1+"px"}));L&&"right"===t&&("top"===x?$("#boussole-"+a).css(t,parseInt(y)+$("#titreVignettes-"+a).height()+4+"px"):$("#boussole-"+a).css(t,parseInt(y)+
"px"));"right"===C&&$("#barre-"+a).css({right:dX1+"px"});L&&"right"===t&&$("#boussole-"+a).css(t,parseInt(y)+"px");break;case "bottom":$("#divVignettes-"+a).css({transform:"translateY("+($("#divVignettes-"+a).height()+5)+"px)"}),$("#titreVignettes-"+a).css({transform:"translateY("+($("#divVignettes-"+a).height()+5)+"px)"}),dY1=parseInt(ta),"bottom"===K&&("right"===C?$("#barre-"+a).css({top:-(35+dY1-2+$("#titreVignettes-"+a).height())+"px"}):$("#barre-"+a).css({top:-(35+dY1-2)+"px"})),L&&"bottom"===
x&&("right"===t?$("#boussole-"+a).css(x,parseInt(U)+10+$("#titreVignettes-"+a).height()+"px"):$("#boussole-"+a).css(x,parseInt(U)+10+"px"))}else switch(r){case "left":$("#divVignettes-"+a).css({transform:"translateX(0px)"});$("#titreVignettes-"+a).css({transform:"rotate(90deg)"});dX1=parseInt(J)+c;$("#divPrecedent-"+a).css("left",c+6);$("#divPrecedent-"+a).css("left",c+6);dX1=parseInt(J)+parseInt(e)+5;"left"===C&&("top"===K?$("#barre-"+a).css({left:dX1+$("#titreVignettes-"+a).height()+4+"px"}):$("#barre-"+
a).css({left:dX1+"px"}));L&&"left"===t&&("top"===x?$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+$("#titreVignettes-"+a).height()+4+"px"):$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+"px"));break;case "right":$("#divVignettes-"+a).css({transform:"translateX(0px)"});$("#titreVignettes-"+a).css({transform:"rotate(90deg)"});dX1=parseInt(J)+c;$("#divSuivant-"+a).css("right",c+6);"right"===C&&("top"===K?$("#barre-"+a).css({right:dX1+$("#titreVignettes-"+a).height()+4+"px"}):$("#barre-"+a).css({right:dX1+
"px"}));L&&"right"===t&&("top"===x?$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+$("#titreVignettes-"+a).height()+4+"px"):$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+"px"));break;case "bottom":$("#divVignettes-"+a).css({transform:"translateY(0px)"}),$("#titreVignettes-"+a).css({transform:"translateY(0px)"}),dY1=parseInt(ta)+$("#divVignettes-"+a).height()+5,"bottom"===K&&("right"===C?$("#barre-"+a).css({top:-(35+dY1-2+$("#titreVignettes-"+a).height())+NaN}):$("#barre-"+a).css({top:-(35+dY1-
2)+"px"})),"bottom"===r&&L&&"bottom"===x&&("right"===t?$("#boussole-"+a).css(x,parseInt(U)+parseInt(e)/2+5+$("#titreVignettes-"+a).height()+10+"px"):$("#boussole-"+a).css(x,parseInt(U)+parseInt(e)/2+15+"px"))}0<w&&nc()}function cd(){fb="horizontales";$("#hautVignettes-"+a).hide();$("#basVignettes-"+a).hide();$("<div>",{id:"vignettes-"+a,class:"vignettes"}).appendTo("#divVignettes-"+a);var c=e/2,k=$("#pano1-"+a).width()-15;k<(e+10)*p.length&&($("#gaucheVignettes-"+a).show(500),$("#gaucheVignettes-"+
a).css({left:0,height:e/2+6,width:15,bottom:0}),$("#droiteVignettes-"+a).show(500),$("#droiteVignettes-"+a).css({right:"0px",height:e/2+6,width:15,bottom:0}));$("#divVignettes-"+a).css(r,"0px");$("#divVignettes-"+a).css({height:c,width:k,paddingLeft:"17px",paddingTop:"3px",paddingBottom:"3px",backgroundColor:ua,opacity:va,overflow:"hidden"});paddingTitre=2;$("#titreVignettes-"+a).css({width:"80px",height:"30px",bottom:c+5,right:0,padding:paddingTitre+"px",backgroundColor:ua,color:Ua,opacity:va,textAlign:"center"});
$("#vignettes-"+a).css({height:c,width:3E3});$("#divVignettes-"+a).css(r,"0px");for(c=0;c<p.length;c++)texte=""!==p[c].txt?p[c].txt:p[c].xml,$("<img>",{id:"imgVig"+c+"-"+a,class:"imgVignette",src:p[c].image,title:p[c].txt,width:e,height:e/2}).appendTo("#vignettes-"+a);"bottom"===r&&L&&"bottom"===x&&("right"===t?$("#boussole-"+a).css(x,parseInt(U)+parseInt(e)/2+5+$("#titreVignettes-"+a).height()+2*paddingTitre+"px"):$("#boussole-"+a).css(x,parseInt(U)+parseInt(e)/2+15+"px"));$("#divVignettes-"+a).show();
$("#titreVignettes-"+a).show()}function dd(){fb="verticales";$("#gaucheVignettes-"+a).hide();$("#droiteVignettes-"+a).hide();$("<div>",{id:"vignettes-"+a,class:"vignettes"}).appendTo("#divVignettes-"+a);var c=$("#pano1-"+a).height()-15,k=e+5;c<(e+10)/2*p.length&&($("#hautVignettes-"+a).show(500),$("#hautVignettes-"+a).css({left:0,top:0,height:15,width:e+11}),$("#basVignettes-"+a).show(500),$("#basVignettes-"+a).css({left:0,height:15,width:e+11,bottom:0}));$("#divVignettes-"+a).css(r,"0px");$("#divVignettes-"+
a).css({height:c-($("#info-"+a).height()-10)-22,width:k,paddingLeft:"3px",paddingTop:"17px",paddingRight:"3px",backgroundColor:ua,opacity:va,overflow:"hidden",top:$("#info-"+a).height()+10+"px"});paddingTitre=2;$("#titreVignettes-"+a).css({width:"80px",height:"30px",top:$("#info-"+a).height()+10+"px",padding:paddingTitre+"px",backgroundColor:ua,color:Ua,opacity:va,transformOrigin:"0% 0%",transform:"rotate(90deg)",textAlign:"center"});"left"===r?$("#titreVignettes-"+a).css(r,k+5+2*paddingTitre+$("#titreVignettes-"+
a).height()+"px"):$("#titreVignettes-"+a).css(r,k+5-2*paddingTitre-$("#titreVignettes-"+a).width()+"px");$("#vignettes-"+a).css({height:3E3,width:k});$("#divVignettes-"+a).css(r,"0px");for(c=0;c<p.length;c++)texte=""!==p[c].txt?p[c].txt:p[c].xml,$("<img>",{id:"imgVig"+c+"-"+a,class:"imgVignette",src:p[c].image,title:p[c].txt,width:e,height:e/2}).appendTo("#vignettes-"+a).css({marginBottom:"2px",marginTop:"2px",marginLeft:"0px",paddingRight:"0px"});$("#divVignettes-"+a).show();$("#titreVignettes-"+
a).show();"right"===r&&($("#divSuivant-"+a).css("right",k+6),dX1=parseInt(J)+parseInt(e)+5,"right"===C&&("top"===K?$("#barre-"+a).css({right:dX1+$("#titreVignettes-"+a).height()+2*paddingTitre+"px"}):$("#barre-"+a).css({right:dX1+"px"})),L&&"right"===t&&("top"===x?$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+$("#titreVignettes-"+a).height()+2*paddingTitre+"px"):$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+"px")));"left"===r&&($("#divPrecedent-"+a).css("left",k+6),dX1=parseInt(J)+parseInt(e)+
5,"left"===C&&("top"===K?$("#barre-"+a).css({left:dX1+$("#titreVignettes-"+a).height()+2*paddingTitre+"px"}):$("#barre-"+a).css({left:dX1+"px"})),L&&"left"===t&&("top"===x?$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+$("#titreVignettes-"+a).height()+2*paddingTitre+"px"):$("#boussole-"+a).css(t,parseInt(y)+parseInt(e)+5+"px")))}function B(){$("#boutons-"+a).show();$("#info-"+a).show();89.99<l&&(l=89.99);-90>l&&(l=-90);q%=360;Va();gb=THREE.Math.degToRad(90-l);oc=THREE.Math.degToRad(q);Wa.x=500*
Math.sin(gb)*Math.cos(oc);Wa.y=500*Math.cos(gb);Wa.z=500*Math.sin(gb)*Math.sin(oc);M.lookAt(Wa);Xa&&M.position.copy(Wa).negate();z.render(V,M);var c=q-Ba;"oui"===hb?$("#bousAig-"+a).css({transform:"rotate("+c+"deg)"}):$("#bousImg-"+a).css({transform:"rotate("+-c+"deg)"});ib&&Ya&&(angleRadar=g/180*Math.PI/2,c=document.getElementById("radar-"+a),c.getContext&&(c=c.getContext("2d"),c.clearRect(0,0,2*v,2*v),c.fillStyle=Za,c.strokeStyle=$a,c.strokeWidth=1,c.beginPath(),c.moveTo(v,v),c.arc(v,v,v,-angleRadar,
angleRadar,!1),c.lineTo(v,v),c.closePath(),c.fill(),c.stroke()),angleRadar=q-Ba+Ca-90,$("#radar-"+a).css({transform:"rotate("+angleRadar+"deg)"}))}function ed(c){var k=$("#pano1-"+a).width(),b=$("#pano1-"+a).height();posX=Math.round(.1*k);posY=Math.round(.1*b);var d=new Image;d.src=c;d.onload=function(){var e=d.height,f=d.width;ratio=f/e;(k-2*posX)/ratio>b-2*posY?(e=b-2*posY,f=Math.round(e*ratio)):(f=k-2*posX,e=Math.round(f/ratio));mrgX=Math.round((k-2*posX-f)/2)-20;mrgY=Math.round((b-2*posY-e)/2)-
20;$("#divImage-"+a).html("");$("#divImage-"+a).css({width:Math.round(k-2*posX)+"px",height:Math.round(b-2*posY)+"px",padding:posY+"px "+posX+"px",top:"0px",left:"0px",zIndex:10010,opacity:0,backgroundColor:jb});$("<img>",{id:"hsImg-"+a,class:"hsImg",src:c,title:"",style:"background-color : #fff;padding : 20px;box-shadow: 10px 10px 20px 0px #656565;"}).appendTo("#divImage-"+a);$("#hsImg-"+a).css({width:f+"px",height:e+"px",marginTop:mrgY+"px",marginLeft:mrgX+"px"});topCroix=b-e-posY-mrgY-15-40;rightCroix=
k-f-posX-mrgX-15-40;$("<img>",{id:"imgFerme-"+a,class:"imgFerme",src:"panovisu/images/fermer.png",style:"cursor : pointer;height :30px;width : 30px;position : absolute;top:"+topCroix+"px;right : "+rightCroix+"px;",title:"Cliquez pour quitter"}).appendTo("#divImage-"+a);$("#divImage-"+a).show();$("#divImage-"+a).animate({opacity:1},1500)}}function fd(c){var k=$("#pano1-"+a).width(),b=$("#pano1-"+a).height();posX=Math.round(.02*k);posY=Math.round(.02*b);$("#divHTML-"+a).html("");$("#divHTML-"+a).css({width:Math.round(k-
2*posX)+"px",height:Math.round(b-2*posY)+"px",padding:posY+"px "+posX+"px",top:"0px",left:"0px",zIndex:10010,opacity:0,backgroundColor:"rgba(0,0,0,0.7)"});$("<iframe>",{id:"hsHTML-"+a,class:"hsHTML",src:c,height:Math.round(b-2*posY)+"px",width:Math.round(k-2*posX)+"px"}).appendTo("#divHTML-"+a);$("<img>",{id:"imgFerme-"+a,class:"imgFerme",src:"panovisu/images/fermer.png",style:"height :30px;width : 30px;position : absolute;top : 10px;right : 15px;"}).appendTo("#divHTML-"+a);$("#divHTML-"+a).show();
$("#divHTML-"+a).animate({opacity:1},1500)}function Da(){g>Ea&&(g=Ea);g<pc&&(g=pc);M.fov=g;M.updateProjectionMatrix();B()}function ca(c,k){$("#barre-"+a+" button").css({height:"30px",width:"30px",borderRadius:"3px"});$("#barre-"+a+" button img").css({height:"26px",width:"26px",paddingBottom:"0px",marginLeft:"0px"});$("#barre-"+a).css({height:"40px"});$("#button-"+a).show();setTimeout(function(){w1=$("#barre-"+a).width();h1=$("#barre-"+a).height();dX1=parseInt(J);dY1=parseInt(ta)-2;kb&&("right"!==
r||"right"!==C||H||(dX1=parseInt(J)+parseInt(e)+5),"left"!==r||"left"!==C||H||(dX1=parseInt(J)+parseInt(e)+5),"bottom"!==r||"bottom"!==K||H||(dY1=parseInt(ta)-2+parseInt(e)/2+5));switch(C){case "left":$("#barre-"+a).css({left:dX1+"px"});break;case "center":posX=(c-w1)/2+dX1;$("#barre-"+a).css({left:posX+"px"});break;case "right":$("#barre-"+a).css({right:dX1+"px"})}switch(K){case "top":posY=-(k-dY1);$("#barre-"+a).css({top:posY+"px"});break;case "center":posY=-(k+h1)/2-dY1;$("#barre-"+a).css({top:posY+
"px"});break;case "bottom":$("#barre-"+a).css({top:-(35+dY1)+"px"})}},200)}function Lc(){element=document.getElementById("panovisu-"+a);screenfull.enabled&&screenfull.toggle(element);setTimeout(function(){da()},300)}function Mc(){posGauche=(f.width()-$("#infoPanovisu-"+a).width())/2;posHaut=(f.height()-$("#infoPanovisu-"+a).height())/2;$("#infoPanovisu-"+a).css({top:posHaut+"px",left:posGauche+"px"});n&&$("#infoPanovisu-"+a).css({display:"block"})}function Nc(){posGauche=(f.width()-$("#aidePanovisu-"+
a).width())/2;posHaut=(f.height()-$("#aidePanovisu-"+a).height())/2;$("#aidePanovisu-"+a).css({top:posHaut+"px",left:posGauche+"px"});W&&$("#aidePanovisu-"+a).css({display:"block"})}function qc(){panoInfo="<b>Panovisu version "+version+"</b><br><span style='color : red; font-weight : bold;'>D\u00e9sol\u00e9 votre navigateur ne supporte pas Webgl & Canvas</span><br>\n\r\n                Veuillez opter pour un navigateur plus r\u00e9cent<br>\n\r\n                Internet Explorer 10+ / Firefox / Chrome / Op\u00e9ra / Safari<br><br>\n\r\n        &copy; Laurent LANG (2014)";
$("#infoPanovisu-"+a).css({width:"450px",height:"150px"});posGauche=(f.width()-$("#infoPanovisu-"+a).width())/2;posHaut=(f.height()-$("#infoPanovisu-"+a).height())/2;$("#infoPanovisu-"+a).css({top:posHaut+"px",left:posGauche+"px"});$("#infoPanovisu-"+a).html(panoInfo)}function Oc(a,k,b,d){l+=k;g+=d;1===k&&l>a&&(l=a);-1===k&&l<a&&(l=a);1===d&&g>b&&(g=b);-1===d&&g<b&&(g=b);if(l!==a||g!==b)M=new THREE.PerspectiveCamera(g,f.width()/f.height(),1,1100),M.fov=g,M.updateProjectionMatrix(),B(),setTimeout(function(){Oc(a,
k,b,d);Fa=!1},5)}function Pc(a,k){sensLat=a>l?1:-1;sensVisuel=k>g?1:-1;setTimeout(function(){Oc(a,sensLat,k,sensVisuel)},5)}function gd(c){if(0<w){for(b=0;b<w;b++)if($("<div>",{id:"imageFond-"+b+"-"+a,class:"imgFond"}).appendTo("#panovisu-"+a),""!==h[b].tailleX?$("<img>",{id:"imgFond-"+b+"-"+a,width:h[b].tailleX,height:h[b].tailleY,src:h[b].fichier,title:h[b].infobulle}).appendTo("#imageFond-"+b+"-"+a):$("<img>",{id:"imgFond-"+b+"-"+a,src:h[b].fichier,title:h[b].infobulle}).appendTo("#imageFond-"+
b+"-"+a),$("#imgFond-"+b+"-"+a).css({opacity:h[b].opacite}),""!==h[b].url){var k=h[b].url;$("#imgFond-"+b+"-"+a).css({cursor:"pointer",opacity:h[b].opacite});$("#imgFond-"+b+"-"+a).on("click",function(){window.open(k)})}nc()}$(".barre button").css("margin-right",Qc);if(L){$("#boussole-"+a).css(t,y+"px");$("#boussole-"+a).css(x,U+"px");$("#boussole-"+a).css("opacity",lb);$("#boussole-"+a).css({width:X+"px",height:X+"px"});$("#bousImg-"+a).attr("src","panovisu/images/boussoles/"+mb);var b=Math.round(parseInt(X)/
5),d=Math.round((parseInt(X)-b)/2);$("#bousAig-"+a).css({position:"absolute",top:"0px",left:d+"px",width:b+"px",height:X+"px"});$("#bousImg-"+a).css({width:X+"px",height:X+"px",top:"0px",left:"0px"});$("#boussole-"+a).show()}$("#divSuivant-"+a).hide();$("#divPrecedent-"+a).hide();rc=sc=!0;""!==nb&&($("#divSuivant-"+a).show(),sc=!1);""!==ob&&($("#divPrecedent-"+a).show(),rc=!1);tc&&($("#marcheArret-"+a).css(pb,qb+"px"),$("#marcheArret-"+a).css(rb,sb+"px"),$("#marcheArret-"+a).css({width:wa+"px",height:wa+
"px"}),$("#marcheArret-"+a).css("opacity",tb),$("#MAImg-"+a).attr("src","panovisu/images/MA/"+ub),$("#MAImg-"+a).css({width:wa+"px",height:wa+"px",top:"0px",left:"0px"}),$("#marcheArret-"+a).show(),Na=!0);uc&&($("#reseauxSociaux-"+a).css(vb,wb+"px"),$("#reseauxSociaux-"+a).css(xb,yb+"px"),$("#reseauxSociaux-"+a).css({width:4*(xa+30)+"px",height:xa+"px"}),$("#reseauxSociaux-"+a).css("opacity",zb),$("#RSTW-"+a).attr("src","panovisu/images/reseaux/twitter.png"),$("#RSGO-"+a).attr("src","panovisu/images/reseaux/google.png"),
$("#RSFB-"+a).attr("src","panovisu/images/reseaux/facebook.png"),$("#RSEM-"+a).attr("src","panovisu/images/reseaux/email.png"),$("#RSTW-"+a+", #RSGO-"+a+", #RSFB-"+a+", #RSEM-"+a).css({width:xa+"px",height:xa+"px",top:"0px"}),"non"===Ab&&$("#RSTW-"+a).hide(0),"non"===Bb&&$("#RSGO-"+a).hide(0),"non"===Cb&&$("#RSFB-"+a).hide(0),"non"===Db&&$("#RSEM-"+a).hide(0),$("#reseauxSociaux-"+a).show(),Na=!0);$("#info-"+a).html(Eb);"oui"===Fb?$("#boutons-"+a).show():$("#boutons-"+a).hide();"oui"===Gb?$("#deplacement-"+
a).css({display:"inline-block"}):$("#deplacement-"+a).hide();"oui"===Hb?$("#zoom-"+a).css({display:"inline-block"}):$("#zoom-"+a).hide();"oui"===Ib?$("#outils-"+a).css({display:"inline-block"}):$("#outils-"+a).hide();"oui"===Jb?$("#pleinEcran-"+a).show():$("#pleinEcran-"+a).hide();"oui"===Kb?$("#auto-"+a).show():$("#auto-"+a).hide;"oui"===Lb?$("#souris-"+a).show():$("#souris-"+a).hide();"oui"===Aa?$("#info-"+a).fadeIn(2500):$("#info-"+a).css({display:"none",height:"0px"});ea="%"===Mb?Math.round(Ga*
$("#"+fa).parent().width()):Ga;Y();R="%"===Nb?Math.round(Ha*$("#"+fa).parent().height()):Ha;ea+="px";R+="px";$("#"+c).width(ea);$("#"+c).height(R);f.width(ea);f.height(R);ca(f.width(),f.height());c=(R-$("#divSuivant-"+a).height())/2;$("#divSuivant-"+a).css("top",c);$("#divPrecedent-"+a).css("top",c);Mc();Y();Nc();kb&&(H=!1,"bottom"===r?cd():dd(),mc());if(ib){$("#plan-"+a).html("");$("#plan-"+a).css(ga,"0px");$("#plan-"+a).css({backgroundColor:ab,padding:"10px",top:"0px"});$("<img>",{id:"planAig-"+
a,class:"planAig",src:"panovisu/images/plan/aiguillePlan.png"}).appendTo("#plan-"+a);bousX=bb.split(":")[1];bousY=bb.split(":")[0];$("#planAig-"+a).css(bousY,parseInt(Ob+10)+"px");imageObj=new Image;imageObj.src="panovisu/images/plan/aiguillePlan.png";$("#planAig-"+a).css(bousX,parseInt(Pb+10+imageObj.height/2)+"px");$("#planAig-"+a).css({transform:"rotate("+Ca+"deg)"});$("<img>",{id:"planImg-"+a,class:"planImg",src:Qb,width:Rb}).appendTo("#plan-"+a);c=$("#info-"+a).height()+10;$("#plan-"+a).css("top",
c);$("<canvas>",{id:"radar-"+a,class:"radar"}).appendTo("#plan-"+a);transformTitre=$("#planTitre-"+a).css("transform");$("#planTitre-"+a).css({width:"160px",height:"30px",textAlign:"center",paddingLeft:"6px",transformOrigin:"0 0",transform:"rotate(90deg)",backgroundColor:ab,color:Sb,top:c});$("#planTitre-"+a).show();$("#planTitre-"+a).html(chainesTraduction[u].plan);"left"===ga?($("#planTitre-"+a).css(ga,$("#planImg-"+a).width()+20+$("#planTitre-"+a).height()+"px"),kc()):($("#planTitre-"+a).css(ga,
$("#planImg-"+a).width()+20-$("#planTitre-"+a).width()-parseInt($("#planTitre-"+a).css("paddingLeft"))+"px"),lc());$("#radar-"+a).attr("width",2*v);$("#radar-"+a).attr("height",2*v);$("#radar-"+a).css({transformOrigin:"50% 50%"});c=g/180*Math.PI/2;$("#radar-"+a).css({opacity:Tb});Ya&&(b=document.getElementById("radar-"+a),b.getContext&&(b=b.getContext("2d"),b.fillStyle=Za,b.strokeStyle=$a,b.beginPath(),b.moveTo(v,v),b.arc(v,v,v,-c,c,!1),b.lineTo(v,v),b.closePath(),b.fill(),b.stroke()),c=q-Ba+Ca);
for(var b=0;b<D.length;b++)"actif"===D[b].xml?($("<img>",{id:"planPt-"+b+"-"+a,class:"planPoint actif",src:"panovisu/images/plan/pointActif.png",width:"12"}).appendTo("#plan-"+a),Ya&&(Rc=D[b].positX-v+10,Sc=D[b].positY-v+10,$("#radar-"+a).css({top:Sc,left:Rc,transform:"rotate("+c+"deg)"}))):$("<img>",{id:"planPt-"+b+"-"+a,class:"planPoint",title:D[b].texte,src:"panovisu/images/plan/point.png",width:"12"}).appendTo("#plan-"+a),$("#planPt-"+b+"-"+a).css({top:D[b].positY-$("#planPt-"+b+"-"+a).width()/
2+10,left:D[b].positX-$("#planPt-"+b+"-"+a).width()/2+10});$("#plan-"+a).show();$("#planTitre-"+a).show()}}function vc(){var c=[];for(d=0;5>d;d++)c[d]={};$.contextMenu("destroy");wc&&(xc&&(c[0]={suiv:{name:chainesTraduction[u].panoSuivant,disabled:function(a,b){return sc}},prec:{name:chainesTraduction[u].panoPrecedent,disabled:function(a,b){return rc}}}),yc&&(c[1]={little:{name:chainesTraduction[u].petitePlanete,disabled:function(a,b){return Ub}},normal:{name:chainesTraduction[u].vueNoramale,disabled:function(a,
b){return Vb}}}),zc&&(c[2]={sep1:"---------",pers1:{name:Wb}},Ac&&(c[3]={pers2:{name:Xb}})));c[4]={sep2:"---------",lm360:{name:"Le Monde \u00e0\u00a0 360\u00b0"},apropos:{name:chainesTraduction[u].aPropos}};items=$.extend(c[0],c[1],c[2],c[3],c[4]);$.contextMenu({selector:"#panovisu-"+a,className:"data-title",appendTo:"#container-"+a,zIndex:15E3,position:function(c,b,d){c.$menu.css({top:d-$("#container-"+a).offset().top,left:b-$("#container-"+a).offset().left})},callback:function(c,b){switch(c){case "lm360":window.open("http://lemondea360.fr");
break;case "pers1":window.open(Yb);break;case "pers2":window.open(Zb);break;case "suiv":S.fadeOut(1E3,function(){clearInterval(Z);l=q=0;g=75;$("#infoBulle-"+a).hide();$("#infoBulle-"+a).html("");T=!0;ja();A=nb;m=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#divVignettes-"+a).html("");$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();ka(A)});break;case "prec":S.fadeOut(1E3,function(){clearInterval(Z);l=q=0;g=75;$("#infoBulle-"+
a).hide();$("#infoBulle-"+a).html("");T=!0;ja();A=ob;m=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#divVignettes-"+a).html("");$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();ka(A)});break;case "apropos":n?$("#infoPanovisu-"+a).fadeOut(1E3,function(){$("#infoPanovisu-"+a).css({display:"none"});n=!1}):(W&&$("#aidePanovisu-"+a).fadeOut(1E3,function(){W=!1}),$("#infoPanovisu-"+a).fadeIn(1E3,function(){n=!0}));break;case "little":Ub=
!0;Vb=!1;Tc=g;Uc=Ea;Ea=170;Xa=!0;Pc(-90,145);break;case "normal":Ub=!1,Vb=!0,Ea=Uc,Xa=!1,Pc(0,Tc)}Fa=!1},items:items});$(".data-title").attr("data-menutitle","PanoVisu "+version+" - "+programmeur+"("+anneeProgramme+")")}function Vc(a,k){if(k<cb){la=new THREE.TextureLoader;var b=s.split("/")[0]+"/niveau"+k+"/"+s.split("/")[1];la.load(b+".jpg",function(d){if(d.image.width<=ma){var e=b.split("/")[2],f=s.split("/")[1];if(e===f){e=aa?new THREE.SphereGeometry(405-k,200,200):new THREE.SphereGeometry(405-
k,40,40);d=new THREE.MeshBasicMaterial({map:d,overdraw:!0});d=new THREE.Mesh(e,d);d.scale.x=-1;V.add(d);e=0;for(f=d.geometry.vertices.length;e<f;e++){var g=d.geometry.vertices[e];g.normalize();g.multiplyScalar(550-k)}k+=1;Vc(a,k);B()}}})}else la=new THREE.TextureLoader,b=s,la.load(b+".jpg",function(a){if(a.image.width<=ma){var c=b.split("/")[1],k=s.split("/")[1];if(c===k){c=aa?new THREE.SphereGeometry(390,200,200):new THREE.SphereGeometry(390,40,40);a=new THREE.MeshBasicMaterial({map:a,overdraw:!0});
a=new THREE.Mesh(c,a);a.scale.x=-1;V.add(a);c=0;for(k=a.geometry.vertices.length;c<k;c++){var d=a.geometry.vertices[c];d.normalize();d.multiplyScalar(545)}B()}}})}function hd(){M=new THREE.PerspectiveCamera(g,f.width()/f.height(),1,1100);V=new THREE.Scene;if("oui"===Ia){la=new THREE.TextureLoader;var a=s.split("/")[0]+"/niveau0/"+s.split("/")[1];la.load(a+".jpg",function(a){T||(supportWebgl()?z=new THREE.WebGLRenderer:supportCanvas()?(z=new THREE.CanvasRenderer,aa=!1):qc());var b=aa?new THREE.SphereGeometry(405,
200,200):new THREE.SphereGeometry(405,40,40);if(aa){var c=z.context;ma=c.getParameter(c.MAX_TEXTURE_SIZE)}else ma=4096;a=new THREE.MeshBasicMaterial({map:a,overdraw:!0});E=new THREE.Mesh(b,a);E.scale.x=-1;V.add(E);b=0;for(a=E.geometry.vertices.length;b<a;b++)c=E.geometry.vertices[b],c.normalize(),c.multiplyScalar(550);Vc(s,1);z.setSize(f.width(),f.height());$b.append(z.domElement);for(b=0;b<m.length;b++)a=m[b],Bc(a.long,a.lat,a.contenu,a.image,b);Z=setInterval(function(){Va()},100);da();B();ca(f.width(),
f.height());Y();vc();S.fadeIn(500);"oui"===ha&&db()})}else la=new THREE.TextureLoader,la.load(s+".jpg",function(a){T||(supportWebgl()?z=new THREE.WebGLRenderer:supportCanvas()?(z=new THREE.CanvasRenderer,aa=!1):qc());if(aa){var b=new THREE.SphereGeometry(405,200,200),c=z.context;ma=c.getParameter(c.MAX_TEXTURE_SIZE)}else b=new THREE.SphereGeometry(405,40,40),ma=4096;a=new THREE.MeshBasicMaterial({map:a,overdraw:!0});E=new THREE.Mesh(b,a);E.scale.x=-1;V.add(E);b=0;for(a=E.geometry.vertices.length;b<
a;b++)c=E.geometry.vertices[b],c.normalize(),c.multiplyScalar(550);z.setSize(f.width(),f.height());$b.append(z.domElement);for(b=0;b<m.length;b++)a=m[b],Bc(a.long,a.lat,a.contenu,a.image,b);Z=setInterval(function(){Va()},50);da();B();ca(f.width(),f.height());Y();vc();S.fadeIn(500);"oui"===ha&&db()})}function O(a,d){var b=new THREE.Texture(na),e=new THREE.MeshBasicMaterial({map:b,overdraw:!0}),g=new Image;g.onload=function(){var e=a.split("/")[2].split("_")[0],g=s.split("/")[1].split("_")[0];if(e===
g){b.image=this;b.needsUpdate=!0;ia+=1;if(6>ia)$(".panovisuCharge").html(ia+"/6");else if($(".panovisuCharge").html("&nbsp;"),ca(f.width(),f.height()),Y(),B(),"oui"===Ia&&d<cb-1){d+=1;e=s.split("/")[0]+"/niveau"+d+"/"+s.split("/")[1];e=[O(e+"_r.jpg",d),O(e+"_l.jpg",d),O(e+"_u.jpg",d),O(e+"_d.jpg",d),O(e+"_f.jpg",d),O(e+"_b.jpg",d)];ia=0;var h=new THREE.Mesh(new THREE.CubeGeometry(405-d,405-d,405-d,10,10,10),new THREE.MeshFaceMaterial(e));h.scale.x=-1;V.add(h);e=0;for(g=h.geometry.vertices.length;e<
g;e++){var l=h.geometry.vertices[e];l.normalize();l.multiplyScalar(550-d)}}else for(e=[P(s+"_r.jpg"),P(s+"_l.jpg"),P(s+"_u.jpg"),P(s+"_d.jpg"),P(s+"_f.jpg"),P(s+"_b.jpg")],h=new THREE.Mesh(new THREE.CubeGeometry(395,395,395,10,10,10),new THREE.MeshFaceMaterial(e)),h.scale.x=-1,V.add(h),e=0,g=h.geometry.vertices.length;e<g;e++)l=h.geometry.vertices[e],l.normalize(),l.multiplyScalar(550-d);da();B();ca(f.width(),f.height());Y()}};g.src=a;return e}function P(a){var d=new THREE.Texture(na),b=new THREE.MeshBasicMaterial({map:d,
overdraw:!0}),e=new Image;e.onload=function(){d.image=this;d.needsUpdate=!0;ia+=1;6>ia?$(".panovisuCharge").html(ia+"/6"):($(".panovisuCharge").html("&nbsp;"),ca(f.width(),f.height()),Y());da();B();ca(f.width(),f.height());Y()};e.src=a;return b}function jd(){$(".panovisuCharge").html("0/6");M=new THREE.PerspectiveCamera(g,f.width()/f.height(),1,1100);V=new THREE.Scene;aa=!1;if(!T){na=document.createElement("canvas");na.width=128;na.height=128;var a=na.getContext("2d");a.fillStyle="rgb( 128, 128, 128 )";
a.fillRect(0,0,na.width,na.height);supportWebgl()?(z=new THREE.WebGLRenderer,aa=!0):supportCanvas()?z=new THREE.CanvasRenderer:qc()}aa?(a=z.context,ma=a.getParameter(a.MAX_TEXTURE_SIZE)):ma=4096;"oui"===Ia?(a=s.split("/")[0]+"/niveau0/"+s.split("/")[1],a=[O(a+"_r.jpg",0),O(a+"_l.jpg",0),O(a+"_u.jpg",0),O(a+"_d.jpg",0),O(a+"_f.jpg",0),O(a+"_b.jpg",0)]):a=[P(s+"_r.jpg"),P(s+"_l.jpg"),P(s+"_u.jpg"),P(s+"_d.jpg"),P(s+"_f.jpg"),P(s+"_b.jpg")];E=new THREE.Mesh(new THREE.CubeGeometry(405,405,405,10,10,10),
new THREE.MeshFaceMaterial(a));E.scale.x=-1;V.add(E);for(var a=0,d=E.geometry.vertices.length;a<d;a++){var b=E.geometry.vertices[a];b.normalize();b.multiplyScalar(550)}z.setSize(f.width(),f.height());$b.append(z.domElement);setTimeout(function(){for(var a=0;a<m.length;a++){var b=m[a];Bc(b.long,b.lat,b.contenu,b.image,a)}da();B();ca(f.width(),f.height());Y();vc();Z=setInterval(function(){Va()},50);S.fadeIn(500);"oui"===ha&&db()},1E3)}function Y(){if("oui"===Aa){var c=f.width(),d=Ja;"%"===ac&&(d=(c-
10)*Ja);$("#info-"+a).css({fontFamily:"'"+bc+"',Verdana,Arial,sans-serif",fontSize:cc,color:dc,backgroundColor:ec,width:d+"px",display:"block"});d=Ja;"%"===ac&&(d=c*Ja);d=(c-d)/2;$("#info-"+a).css({marginLeft:d})}}function nc(){for(d=0;d<w;d++){switch(h[d].posX){case "left":if(!H&&ya&&"left"===r){var c=parseInt(h[d].offsetX)+Math.round(e)+10;$("#imageFond-"+d+"-"+a).css(h[d].posX,c+"px")}else $("#imageFond-"+d+"-"+a).css(h[d].posX,parseInt(h[d].offsetX)+"px");break;case "right":!H&&ya&&"right"===
r?(c=parseInt(h[d].offsetX)+Math.round(e)+10,$("#imageFond-"+d+"-"+a).css(h[d].posX,c+"px")):$("#imageFond-"+d+"-"+a).css(h[d].posX,h[d].offsetX+"px");break;case "center":c=($("#panovisu-"+a).width()-$("#imgFond-"+d+"-"+a).width())/2+parseInt(h[d].offsetX),$("#imageFond-"+d+"-"+a).css("left",c+"px")}"middle"!==h[d].posY?!H&&ya&&"bottom"===r&&"bottom"===h[d].posY?(c=parseInt(h[d].offsetY)+Math.round(e/2)+10,$("#imageFond-"+d+"-"+a).css(h[d].posY,c+"px")):$("#imageFond-"+d+"-"+a).css(h[d].posY,h[d].offsetY+
"px"):(c=($("#panovisu-"+a).height()-$("#imgFond-"+d+"-"+a).height())/2+parseInt(h[d].offsetY),$("#imageFond-"+d+"-"+a).css("top",c+"px"))}}function da(){fc?(ea=screen.width,R=screen.height):(ea="%"===Mb?Math.round(Ga*$("#"+fa).parent().width()):Ga,R="%"===Nb?Math.round(Ha*$("#"+fa).parent().height()):Ha,$("#"+fa).css({width:ea+"px",height:R+"px"}));f.css({width:ea+"px",height:R+"px"});M.aspect=f.width()/f.height();M.updateProjectionMatrix();z.setSize(f.width(),f.height());B();setTimeout(function(){Mc();
Nc();ca(f.width(),f.height());Y();if(0<p.length&&"horizontales"===fb){var c;c=fc?$("#pano1-"+a).width():$("#pano1-"+a).width()-15;$("#divVignettes-"+a).css({width:c});$("#vignettes-"+a).css({transform:"translate(0px,0px)"});var d=(e+10)*p.length;c<d?($("#gaucheVignettes-"+a).show(),$("#droiteVignettes-"+a).show()):($("#gaucheVignettes-"+a).hide(),$("#droiteVignettes-"+a).hide())}0<p.length&&"verticales"===fb&&(c=$("#pano1-"+a).height()-($("#info-"+a).height()-10)-37,$("#divVignettes-"+a).css({height:c}),
$("#vignettes-"+a).css({transform:"translate(0px,0px)"}),d=(e/2+5)*p.length,c<d?($("#hautVignettes-"+a).show(),$("#basVignettes-"+a).show(),$("#hautVignettes-"+a).css({left:0,top:0,height:15,width:e+11}),$("#basVignettes-"+a).css({left:0,height:15,width:e+11,bottom:0})):($("#hautVignettes-"+a).hide(),$("#basVignettes-"+a).hide()));d=(R-$("#divSuivant-"+a).height())/2;$("#divSuivant-"+a).css("top",d);$("#divPrecedent-"+a).css("top",d);0<w&&nc()},300)}function db(){id=requestAnimationFrame(db);!1===
Fa&&(q+=.25);l=Math.max(-85,Math.min(85,l));B()}function Bc(c,d,b,e,f){$("<div>",{id:"HS-"+f+"-"+a,class:"hotSpots"}).appendTo("#panovisu-"+a);$("<img>",{id:"imgHS-"+f+"-"+a,width:"30px",src:e,title:m[f].info}).appendTo("#HS-"+f+"-"+a);N+=1}function ja(){for(var c=0;c<N;c++)$("#HS-"+c+"-"+a).html(),$("#HS-"+c+"-"+a).remove();m=[];N=0}function Va(){pHeight=$("#panovisu-"+a).height();pWidth=$("#panovisu-"+a).width();cLatitude=Math.cos(l*Ka);sLatitude=Math.sin(l*Ka);c1=-pHeight/Math.tan(g*Math.PI/360)/
2;for(var c=0;c<N;c++)deltaLong=q%360-m[c].long,cLat=Math.cos(m[c].lat*Ka),sLat=Math.sin(m[c].lat*Ka),cDeltaLong=Math.cos(deltaLong*Ka),sDeltaLong=Math.sin(deltaLong*Ka),denom=sLat*sLatitude+cLat*cLatitude*cDeltaLong,coef=c1/denom,0>cDeltaLong||Xa?$("#HS-"+c+"-"+a).hide():($("#HS-"+c+"-"+a).show(),top1=coef*(sLat*cLatitude-cLat*sLatitude*cDeltaLong)+pHeight/2-15+"px",left1=coef*sDeltaLong*cLat+pWidth/2-15+"px",$("#HS-"+c+"-"+a).css({top:top1,left:left1}))}function ka(c){$.get(c,function(c){Ub=!1;
Vb=!0;Xa=!1;s="faces";F="none";I="classique";G="none";Eb="";bc="Monospace";dc="#fff";cc="13px";La="50%";ec="#000";Cc="0.5";jb="rgba(0,0,0,0.8)";gc="cube";eb="oui";n=!0;W=!1;Fb=Lb=Kb=Jb=Gb=Ib=Hb=Aa="oui";ha="non";C="center";K="bottom";J="0";ta="10";Ba=0;L=!1;mb="rose2.png";X="120";t="right";x="bottom";U=y="20";hc="non";lb=.75;hb="non";tc=!1;ic="non";tb=.8;ub="MAVert.png";pb="left";rb="bottom";sb=qb=10;wa=30;Ta=Sa=Ra=Pa=Qa=Oa="non";uc=!1;jc="non";zb=.8;vb="left";xb="bottom";yb=wb=0;xa=30;ya=Db=Bb=Cb=
Ab="non";kb=!1;Ia="non";w=cb=0;va=.8;r="bottom";ua="green";Ua="yellow";e=120;p=[];m=[];D=[];ib=!1;Qb="";Ca=Rb=0;ga="left";ab="rgba(0,0,0,0.5)";Dc=.8;Sb="white";bb="top:right";Ob=Pb=0;v=50;Tb=.6;Za="rgb(128,128,128)";$a="rgb(200,200,0)";Ya=!1;yc=xc=wc=!0;Ac=zc=!1;Zb=Yb=Xb=Wb="";$("#divVignettes-"+a).html("");$("<img>",{id:"gaucheVignettes-"+a,class:"positionVignettes",src:"panovisu/images/interface/gauche.jpg"}).appendTo("#divVignettes-"+a);$("<img>",{id:"droiteVignettes-"+a,class:"positionVignettes",
src:"panovisu/images/interface/droite.jpg"}).appendTo("#divVignettes-"+a);$("<img>",{id:"hautVignettes-"+a,class:"positionVignettes",src:"panovisu/images/interface/haut.jpg"}).appendTo("#divVignettes-"+a);$("<img>",{id:"basVignettes-"+a,class:"positionVignettes",src:"panovisu/images/interface/bas.jpg"}).appendTo("#divVignettes-"+a);$("#divVignettes-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#reseauxSociaux-"+a).hide();var b=$(c).find("pano");s=b.attr("image")||s;Eb=b.attr("titre")||
Eb;bc=b.attr("titrePolice")||bc;dc=b.attr("titreCouleur")||dc;La=b.attr("titreTaille")||La;cc=b.attr("titreTaillePolice")||cc;ec=b.attr("titreFond")||ec;Cc=b.attr("titreOpacite")||Cc;jb=b.attr("diaporamaCouleur")||jb;gc=b.attr("type")||gc;Ia=b.attr("multiReso")||Ia;cb=parseInt(b.attr("nombreNiveaux"))||cb;ha=b.attr("rotation")||ha;q=parseFloat(b.attr("regardX"))||q;l=parseFloat(b.attr("regardY"))||l;g=b.attr("champVision")||g;Aa=b.attr("afftitre")||Aa;eb=b.attr("affinfo")||eb;Ba=parseFloat(b.attr("zeroNord"))||
Ba;T&&(eb=!1);n="oui"===eb?!0:!1;b=$(c).find("suivantPrecedent");nb=b.attr("suivant")||"";ob=b.attr("precedent")||"";b=$(c).find("boussole");hc=b.attr("affiche")||hc;L="oui"===hc;mb=b.attr("image")||mb;X=b.attr("taille")||X;t=b.attr("positionX")||t;x=b.attr("positionY")||x;y=b.attr("dX")||y;U=b.attr("dY")||U;lb=parseFloat(b.attr("opacite"))||lb;hb=b.attr("aiguille")||hb;b=$(c).find("menuContextuel");bMCAffiche=b.attr("affiche")||"oui";wc="oui"===bMCAffiche;bPrecSuivMC=b.attr("precSuiv")||"oui";xc=
"oui"===bPrecSuivMC;bPlaneteMC=b.attr("planete")||"oui";yc="oui"===bPlaneteMC;bPersMC1=b.attr("pers1")||"non";zc="oui"===bPersMC1;bPersMC2=b.attr("pers2")||"non";Ac="oui"===bPersMC2;Wb=b.attr("lib1")||Wb;Xb=b.attr("lib2")||Xb;Yb=b.attr("url1")||Yb;Zb=b.attr("url2")||Zb;b=$(c).find("reseauxSociaux");jc=b.attr("affiche")||jc;uc="oui"===jc;zb=parseFloat(b.attr("opacite"))||zb;vb=b.attr("positionX")||vb;xb=b.attr("positionY")||xb;wb=parseFloat(b.attr("dX"))||wb;yb=parseFloat(b.attr("dY"))||yb;xa=parseFloat(b.attr("taille"))||
xa;Ab=b.attr("twitter")||Ab;Cb=b.attr("facebook")||Cb;Bb=b.attr("google")||Bb;Db=b.attr("email")||Db;b=$(c).find("marcheArret");ic=b.attr("affiche")||ic;tc="oui"===ic;ub=b.attr("image")||ub;tb=parseFloat(b.attr("opacite"))||tb;pb=b.attr("positionX")||pb;rb=b.attr("positionY")||rb;qb=parseFloat(b.attr("dX"))||qb;sb=parseFloat(b.attr("dY"))||sb;wa=parseFloat(b.attr("taille"))||wa;Oa=b.attr("navigation")||Oa;Pa=b.attr("boussole")||Pa;Qa=b.attr("titre")||Qa;Ra=b.attr("plan")||Ra;Sa=b.attr("reseaux")||
Sa;Ta=b.attr("vignettes")||Ta;b=$(c).find("boutons");Gb=b.attr("deplacements")||Gb;I=b.attr("styleBoutons")||I;Hb=b.attr("zoom")||Hb;Ib=b.attr("outils")||Ib;Qc=parseInt(b.attr("espacement"))-4||0;Jb=b.attr("fs")||Jb;Kb=b.attr("rotation")||Kb;Lb=b.attr("souris")||Lb;Fb=b.attr("visible")||Fb;C=b.attr("positionX")||C;K=b.attr("positionY")||K;F=b.attr("couleur")||F;G=b.attr("bordure")||G;$("#xmoins-"+a+",#xplus-"+a+",#ymoins-"+a+",#yplus-"+a+",#zoomPlus-"+a+",#zoomMoins-"+a+",#pleinEcran-"+a+",#souris-"+
a+",#auto-"+a+",#binfo-"+a+",#aide-"+a).css({backgroundColor:F,border:"1px solid "+G});J=b.attr("dX")||J;ta=b.attr("dY")||ta;d=0;ja();$(c).find("point").each(function(){m[d]=new Zc;m[d].type=$(this).attr("type")||m[d].type;switch(m[d].type){case "panoramique":m[d].contenu=$(this).attr("xml");break;case "image":m[d].contenu=$(this).attr("img");break;case "html":m[d].contenu=$(this).attr("url")}m[d].info=$(this).attr("info")||"";m[d].image=$(this).attr("image")||"panovisu/images/sprite2.png";m[d].long=
$(this).attr("long")||0;m[d].anime=$(this).attr("anime")||"false";m[d].lat=$(this).attr("lat")||0;d++});b=$(c).find("vignettes");ya=b.attr("affiche")||ya;kb="oui"===ya;va=parseFloat(b.attr("opacite"))||va;r=b.attr("position")||r;ua=b.attr("fondCouleur")||ua;Ua=b.attr("texteCouleur")||Ua;Wc=parseFloat(b.attr("taille"))||Wc;e=parseFloat(b.attr("tailleImage"))||e;d=0;$(c).find("imageVignette").each(function(){p[d]=new $c;p[d].xml=$(this).attr("xml");p[d].image=$(this).attr("image");p[d].txt=$(this).attr("texte")||
"";d++});w=0;h=[];$(".imgFond").remove();$(c).find("imageFond").each(function(){h[w]=new bd;h[w].fichier=$(this).attr("fichier")||"";h[w].url=$(this).attr("url")||"";h[w].infobulle=$(this).attr("infobulle")||"";h[w].tailleX=$(this).attr("tailleX")||"";h[w].tailleY=$(this).attr("tailleY")||"";h[w].posX=$(this).attr("posX")||"right";h[w].posY=$(this).attr("posY")||"bottom";h[w].offsetX=$(this).attr("offsetX")||0;h[w].offsetY=$(this).attr("offsetY")||0;h[w].opacite=$(this).attr("opacite")||0;h[w].masquable=
"oui"===($(this).attr("masquable")||"oui");w++});b=$(c).find("plan");planAff=b.attr("affiche")||"non";ib="oui"===planAff;Qb=b.attr("image")||Qb;ga=b.attr("position")||ga;ab=b.attr("couleurFond")||ab;Sb=b.attr("couleurTexte")||Sb;Dc=parseFloat(b.attr("opacitePlan"))||Dc;Rb=parseFloat(b.attr("largeur"))||Rb;Ca=parseFloat(b.attr("nord"))||Ca;bb=b.attr("boussolePosition")||bb;Pb=parseInt(b.attr("boussoleX"))||Pb;Ob=parseInt(b.attr("boussoleY"))||Ob;afficheRadar=b.attr("radarAffiche")||"non";v=parseInt(b.attr("radarTaille"))||
v;Tb=parseFloat(b.attr("radarOpacite"))||Tb;Za=b.attr("radarCouleurFond")||Za;$a=b.attr("radarCouleurLigne")||$a;Ya="oui"===afficheRadar;d=0;$(c).find("pointPlan").each(function(){D[d]=new ad;D[d].xml=$(this).attr("xml");D[d].texte=$(this).attr("texte")||"";D[d].positX=parseInt($(this).attr("positX"))||0;D[d].positY=parseInt($(this).attr("positY"))||0;d++});La.match("[px]","g")?(ac="px",Ja=parseInt(La)):(ac="%",Ja=parseInt(La)/100);gd(fa);$("#xmoins-"+a).html("");$("<img>",{src:"panovisu/images/"+
I+"/gauche.png",alt:""}).appendTo("#xmoins-"+a);$("#ymoins-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/haut.png",alt:""}).appendTo("#ymoins-"+a);$("#yplus-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/bas.png",alt:""}).appendTo("#yplus-"+a);$("#xplus-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/droite.png",alt:""}).appendTo("#xplus-"+a);$("#zoomPlus-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/zoomin.png",alt:""}).appendTo("#zoomPlus-"+a);$("#zoomMoins-"+a).html("");$("<img>",
{src:"panovisu/images/"+I+"/zoomout.png",alt:""}).appendTo("#zoomMoins-"+a);$("#pleinEcran-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/fs.png",alt:""}).appendTo("#pleinEcran-"+a);$("#souris-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/souris.png",alt:""}).appendTo("#souris-"+a);$("#auto-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/rotation.png",alt:""}).appendTo("#auto-"+a);$("#binfo-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/info.png",alt:""}).appendTo("#binfo-"+a);
$("#aide-"+a).html("");$("<img>",{src:"panovisu/images/"+I+"/aide.png",alt:""}).appendTo("#aide-"+a);switch(gc){case "cube":jd();break;case "sphere":hd()}da()})}var za=window.location.search.substring(1).split("&"),Ec=[],d;for(d in za)-1!==za[d].indexOf("=")?Ec[decodeURI(za[d].substring(0,za[d].indexOf("=")))]=decodeURI(za[d].substring(za[d].indexOf("=")+1)):Ec[decodeURI(za[d])]="";var M,V,z,Q,aa=!0,Rc,Sc,ma,Z,Ma,N=0,T=!1,m=[],p=[],D=[],h=[],w=0,ba,H,oa=1,q=0,l=0,fa,na,Fa=!1,Fc=0,Gc=0,Xc=0,Yc=0,gb=
0,oc=0,g=75,sa=0,ra=0,Hc=0,Ic=0,Ea=125,pc=25,Wa=new THREE.Vector3,fc=!1,ea,R,A,Ga,Ha,Mb,Nb,fb,ia=0,pa=0,qa=0,Uc,Tc,Ub=!1,Vb=!0,Xa=!1,sc,rc,u="fr_FR",Ka=Math.PI/180,s,la,F,nb,ob,I,G,Eb,Ia,cb,bc,La,ac,Ja,cc,dc,ec,Cc,jb,gc,eb,n,W,Aa,Hb,Ib,Gb,Jb,Kb,Lb,Qc,Fb,ha,C,K,J,ta,E,$b,f,S,Ba,L,mb,X,t,x,y,U,hc,lb,hb,Na,tc,ic,ub,tb,pb,rb,qb,sb,Qa,Oa,Pa,Ra,Sa,Ta,wa,uc,jc,zb,vb,xb,wb,yb,xa,Ab,Cb,Bb,Db,ya,kb,va,r,ua,Ua,Wc,e,ib,Rb,Qb,ga,ab,Sb,Dc,Ca,bb,Pb,Ob,Ya,v,Tb,Za,$a,wc,xc,yc,zc,Ac,Wb,Xb,Yb,Zb;$(document).on("webkitfullscreenchange mozfullscreenchange fullscreenchange MSFullscreenChange",
function(){fc=!fc;da()});$(document).on("click",".hotSpots",function(){idHS=$(this).attr("id");Ma=parseInt(idHS.split("-")[1]);console.log(idHS+" num "+Ma);switch(m[Ma].type){case "panoramique":$("#info-"+a).fadeOut(1E3);S.fadeOut(1E3,function(){var c=Ma;clearInterval(Z);l=q=0;g=75;$("#infoBulle-"+a).hide();$("#infoBulle-"+a).html("");T=!0;A=m[c].contenu;ja();m=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#divVignettes-"+a).html("");
$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();ka(A)});break;case "image":ed(m[Ma].contenu);break;case "html":fd(m[Ma].contenu)}});$(document).on("click","#container-"+a,function(a){});$(document).on("mousedown","#container-"+a,function(c){1===c.which&&(n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1}),Fc=c.clientX,Gc=c.clientY,Fa=!0,1===oa?(Ic=Hc=0,clearInterval(Q),Q=setInterval(function(){q+=Hc;l+=Ic;B()},10)):(Xc=q,Yc=l,f.addClass("curseurCroix"),
0===oa&&$("#container-"+a).css("cursor","grabbing")));c.preventDefault()});$(document).on("mousemove","#container-"+a,function(a){!0===Fa&&(1===oa?(Hc=.01*-(Fc-a.clientX),Ic=.01*(Gc-a.clientY)):(Va(),q=.1*(Fc-a.clientX)+Xc,l=.1*(a.clientY-Gc)+Yc,B()));a.preventDefault()});$(document).on("mouseup mouseleave touchend","#container-"+a,function(c){clearInterval(Q);f.removeClass("curseurCroix");Fa=!1;0===oa&&$("#container-"+a).css("cursor","grab")});$(document).on("mouseover","#panovisu-"+a,function(a){});
$(document).on("mouseleave","#panovisu-"+a,function(a){});$(document).on("mousewheel","#container-"+a,function(c,d){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1});c.preventDefault();g-=d;Da()});$(window).resize(function(){da()});$(document).keydown(function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1});c.preventDefault();switch(c.which){case 37:q-=1;break;case 38:l+=1;break;case 39:q+=1;break;case 40:l-=1;break;case 16:g+=
1;break;case 17:g-=1;break;case 70:Lc();break;case 86:H=!H;mc();break;case 80:ba=!ba;"left"===ga?kc():lc();break;case 77:Kc()}Da()});$(document).on("mousedown","#xmoins-"+a+",#xplus-"+a+",#ymoins-"+a+",#yplus-"+a,function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1});Jc($(this).attr("id"));clearInterval(Q);Q=setInterval(function(){q+=sa;l+=ra;B()},50);c.preventDefault()});$(document).on("mouseup mouseleave","#xmoins-"+a+",#xplus-"+a+",#ymoins-"+a+",#yplus-"+
a,function(a){clearInterval(Q);a.preventDefault()});$(document).on("mousedown","#zoomPlus-"+a,function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1});clearInterval(Q);Q=setInterval(function(){g-=1;Da()},100);c.preventDefault()});$(document).on("mouseup mouseleave","#zoomPlus-"+a,function(a){clearInterval(Q);a.preventDefault()});$(document).on("click","#zoomMoins-"+a,function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=
!1});g+=1;Da();c.preventDefault()});$(document).on("mousedown","#zoomMoins-"+a,function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1});clearInterval(Q);Q=setInterval(function(){g+=1;Da()},100);c.preventDefault()});$(document).on("mouseup mouseleave","#zoomMoins-"+a,function(a){clearInterval(Q);a.preventDefault()});$(document).on("click","#xmoins-"+a+",#xplus-"+a+",#ymoins-"+a+",#yplus-"+a,function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});
n=!1});Jc($(this).attr("class"));q+=2*sa;l+=2*ra;B()});$(document).on("click","#zoomPlus-"+a,function(c){n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1});g-=1;Da();c.preventDefault()});$(document).on("click","#souris-"+a,function(){oa=1-oa;0===oa?$("#container-"+a).css("cursor","grab"):$("#container-"+a).css("cursor","default")});$(document).on("click","#pleinEcran-"+a,function(){Lc()});$(document).on("click","#auto-"+a,function(){"oui"===ha?(ha="non",cancelAnimationFrame(id)):
(ha="oui",db())});$(document).on("click",".binfo",function(){n?$("#infoPanovisu-"+a).fadeOut(1E3,function(){$("#infoPanovisu-"+a).css({display:"none"});n=!1}):(W&&$("#aidePanovisu-"+a).fadeOut(1E3,function(){W=!1}),$("#infoPanovisu-"+a).fadeIn(1E3,function(){n=!0}))});$(document).on("click",".aide",function(){W?$("#aidePanovisu-"+a).fadeOut(1E3,function(){$("#aidePanovisu-"+a).css({display:"none"});W=!1}):(n&&$("#infoPanovisu-"+a).fadeOut(1E3,function(){n=!1}),$("#aidePanovisu-"+a).fadeIn(1E3,function(){W=
!0}))});$(document).on("click",".infoPanovisu",function(){$(this).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1})});$(document).on("click",".aidePanovisu",function(){$(this).fadeOut(2E3,function(){$(this).css({display:"none"});W=!1})});$(document).on("click",".infoPanovisu a",function(a){a.stopPropagation()});$(document).on("click",".imgVignette",function(c){if(0!==p.length){c=$(this).attr("id");var d=parseInt(c.substring(6).split("-")[0]);S.fadeOut(1E3,function(){clearInterval(Z);l=q=
0;g=75;$("#infoBulle-"+a).hide();$("#infoBulle-"+a).html("");T=!0;A=p[d].xml;ja();m=[];p=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#divVignettes-"+a).html("");$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();ka(A)})}});$(document).on("click",".positionVignettes",function(c){if(e){c.stopPropagation();element=$(this).attr("id");if(element==="gaucheVignettes-"+a||element==="droiteVignettes-"+a)deplace=e+10,pa=element==="gaucheVignettes-"+
a?pa+deplace:pa-deplace,0<pa&&(pa=0),-pa+$("#divVignettes-"+a).width()>(e+10)*p.length&&(pa=$("#divVignettes-"+a).width()-(e+10)*p.length),$("#vignettes-"+a).css({transform:"translate("+pa+"px,0px)"});if(element==="basVignettes-"+a||element==="hautVignettes-"+a)deplace=e/2+5,qa=element==="hautVignettes-"+a?qa+deplace:qa-deplace,0<qa&&(qa=0),-qa+$("#divVignettes-"+a).height()>(e/2+15)*p.length&&(qa=$("#divVignettes-"+a).height()-(e/2+15)*p.length),$("#vignettes-"+a).css({transform:"translate(0px,"+
qa+"px)"});n&&$("#infoPanovisu-"+a).fadeOut(2E3,function(){$(this).css({display:"none"});n=!1})}});$(document).on("click",".marcheArret",function(a){a.stopPropagation();Kc()});$(document).on("click","#divSuivant-"+a,function(){S.fadeOut(1E3,function(){clearInterval(Z);l=q=0;g=75;$("#infoBulle-"+a).hide();$("#infoBulle-"+a).html("");T=!0;ja();A=nb;m=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#divVignettes-"+a).html("");$("#divVignettes-"+
a).hide();$("#titreVignettes-"+a).hide();ka(A)})});$(document).on("click","#divPrecedent-"+a,function(){S.fadeOut(1E3,function(){clearInterval(Z);l=q=0;g=75;$("#infoBulle-"+a).hide();$("#infoBulle-"+a).html("");T=!0;ja();A=ob;m=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#divVignettes-"+a).html("");$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();ka(A)})});$(document).on("click","#planTitre-"+a,function(){"left"===ga?(ba=
ba?!1:!0,kc()):(ba=ba?!1:!0,lc())});$(document).on("click",".titreVignettes",function(){H=H?!1:!0;mc()});$(document).on("click",".planPoint",function(){if(0!==D.length){var c=parseInt($(this).attr("id").split("-")[1]);A=D[c].xml;"actif"!==A&&S.fadeOut(1E3,function(){clearInterval(Z);l=q=0;g=75;$("#infoBulle-"+a).hide();$("#infoBulle-"+a).html("");ja();T=!0;m=[];p=[];N=0;$("#boussole-"+a).hide();$("#marcheArret-"+a).hide();$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("#divVignettes-"+a).html("");
$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();ka(A)})}});$(document).on("click","#imgFerme-"+a,function(){$("#divHTML-"+a).hide();$("#divImage-"+a).hide()});this.initialisePano=function(c){c=$.extend({langue:"fr_FR",xml:"xml/panovisu.xml",fenX:"75%",fenY:"80%",panoramique:"panovisu",minFOV:35,maxFOV:120},c);fa=c.panoramique;u=c.langue;$("#"+fa).css("overflow","hidden");Ea=c.maxFOV;pc=c.minFOV;var d=fa;$(d).css({overflow:"hidden"});var b="panovisu-"+a;$("<div>",{id:b,class:"panovisu",
style:"width : 100%;height : 100%;position: relative;"}).appendTo("#"+d);$("<div>",{id:"boussole-"+a,class:"boussole"}).appendTo("#"+b);$("<img>",{id:"bousImg-"+a,class:"bousImg",src:""}).appendTo("#boussole-"+a);$("<img>",{id:"bousAig-"+a,class:"bousAig",src:"panovisu/images/boussoles/aiguille.png"}).appendTo("#boussole-"+a);$("#boussole-"+a).hide();$("<div>",{id:"marcheArret-"+a,class:"marcheArret"}).appendTo("#"+b);$("<img>",{id:"MAImg-"+a,class:"MAImg",src:"",title:chainesTraduction[u].afficheMasque}).appendTo("#marcheArret-"+
a);$("#marcheArret-"+a).hide();$("<div>",{id:"reseauxSociaux-"+a,class:"reseauxSociaux"}).appendTo("#"+b);$("<img>",{id:"RSTW-"+a,class:"RS reseauSocial-twitter",src:"",title:"twitter"}).appendTo("#reseauxSociaux-"+a);$("<img>",{id:"RSGO-"+a,class:"RS reseauSocial-google",src:"",title:"google"}).appendTo("#reseauxSociaux-"+a);$("<img>",{id:"RSFB-"+a,class:"RS reseauSocial-fb",src:"",title:"facebook"}).appendTo("#reseauxSociaux-"+a);$("<a>",{id:"lienEmail"+a,class:"RS reseauSocial-email",href:""}).appendTo("#reseauxSociaux-"+
a);$("<img>",{id:"RSEM-"+a,src:"",title:"email"}).appendTo("#lienEmail"+a);$("#reseauxSociaux-"+a).hide();$("<div>",{id:"info-"+a,class:"info"}).appendTo("#"+b);$("<div>",{id:"infoBulle-"+a,class:"infoBulle",style:"display:none;position: absolute;"}).appendTo("#"+b);$("#infoBulle-"+a).html("infoBulle");$("<div>",{id:"pano1-"+a,class:"pano1"}).appendTo("#"+b);$("<div>",{id:"container-"+a,class:"container"}).appendTo("#pano1-"+a);$("<div>",{id:"divVignettes-"+a,class:"vignettes"}).appendTo("#pano1-"+
a);$("<div>",{id:"titreVignettes-"+a,class:"titreVignettes"}).appendTo("#pano1-"+a);$("#titreVignettes-"+a).html(chainesTraduction[u].vignettes);$("#divVignettes-"+a).hide();$("#titreVignettes-"+a).hide();$("<div>",{id:"divImage-"+a,class:"vignettes"}).appendTo("#pano1-"+a);$("#divImage-"+a).hide();$("<div>",{id:"divHTML-"+a,class:"vignettes"}).appendTo("#pano1-"+a);$("#divHTML-"+a).hide();$("<div>",{id:"divPrecedent-"+a,class:"precedent",title:chainesTraduction[u].panoPrecedent}).appendTo("#pano1-"+
a);$("<div>",{id:"divSuivant-"+a,class:"suivant",title:chainesTraduction[u].panoSuivant}).appendTo("#pano1-"+a);$("#divPrecedent-"+a).hide();$("#divSuivant-"+a).hide();ba=!1;H=!0;$("<div>",{id:"boutons-"+a,class:"boutons"}).appendTo("#"+b);$("<div>",{id:"barre-"+a,class:"barre"}).appendTo("#boutons-"+a);$("<div>",{id:"deplacement-"+a,class:"deplacement"}).appendTo("#barre-"+a);$("<div>",{id:"zoom-"+a,class:"zoom"}).appendTo("#barre-"+a);$("<div>",{id:"outils-"+a,class:"outils"}).appendTo("#barre-"+
a);$("<div>",{id:"plan-"+a,class:"plan"}).appendTo("#pano1-"+a);$("<div>",{id:"planTitre-"+a,class:"planTitre"}).appendTo("#pano1-"+a);$("#plan-"+a).hide();$("#planTitre-"+a).hide();$("<button>",{type:"button",id:"xmoins-"+a,class:"xmoins",title:chainesTraduction[u].gauche,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#deplacement-"+a);$("<button>",{type:"button",id:"ymoins-"+a,class:"ymoins",title:chainesTraduction[u].haut,style:"background-color : "+F+";border : 1px solid "+
G+";"}).appendTo("#deplacement-"+a);$("<button>",{type:"button",id:"yplus-"+a,class:"yplus",title:chainesTraduction[u].bas,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#deplacement-"+a);$("<button>",{type:"button",id:"xplus-"+a,class:"xplus",title:chainesTraduction[u].droite,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#deplacement-"+a);$("<button>",{type:"button",id:"zoomPlus-"+a,class:"zoomPlus",title:chainesTraduction[u].zoomPlus,style:"background-color : "+
F+";border : 1px solid "+G+";"}).appendTo("#zoom-"+a);$("<button>",{type:"button",id:"zoomMoins-"+a,class:"zoomMoins",title:chainesTraduction[u].zoomMoins,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#zoom-"+a);$("<button>",{type:"button",id:"pleinEcran-"+a,class:"pleinEcran",title:chainesTraduction[u].pleinEcran,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#outils-"+a);$("<button>",{type:"button",id:"souris-"+a,class:"souris",title:chainesTraduction[u].souris,
style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#outils-"+a);$("<button>",{type:"button",id:"auto-"+a,class:"auto",title:chainesTraduction[u].autoratation,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#outils-"+a);$("<button>",{type:"button",id:"binfo-"+a,class:"binfo",title:chainesTraduction[u].aPropos,style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#outils-"+a);$("<button>",{type:"button",id:"aide-"+a,class:"aide",title:chainesTraduction[u].aide,
style:"background-color : "+F+";border : 1px solid "+G+";"}).appendTo("#outils-"+a);$("<div>",{id:"infoPanovisu-"+a,class:"infoPanovisu"}).appendTo("#"+b);$("#infoPanovisu-"+a).hide();panoInfo=chainesTraduction[u].fenetreInfo;$("#infoPanovisu-"+a).css({width:"450px",height:"190px"});$("#infoPanovisu-"+a).html(panoInfo);$("<div>",{id:"aidePanovisu-"+a,class:"aidePanovisu"}).appendTo("#"+b);$("#aidePanovisu-"+a).hide();panoInfo=chainesTraduction[u].fenetreAide;$("#aidePanovisu-"+a).css({width:"400px",
height:"220px"});$("#aidePanovisu-"+a).html(panoInfo);$b=$("#container-"+a);f=$("#"+b);S=$("#pano1-"+a);$("#planTitre-"+a).css("transform","rotate(90deg)");A=Ec.xml||c.xml;c.fenX.match("[px]","g")?(Mb="px",Ga=parseInt(c.fenX)):(Mb="%",Ga=parseInt(c.fenX)/100);c.fenY.match("[px]","g")?(Nb="px",Ha=parseInt(c.fenY)):(Nb="%",Ha=parseInt(c.fenY)/100);estTactile()&&(oa=0);ka(A)}}$("head").append($(document.createElement("link")).attr({rel:"stylesheet",type:"text/css",href:"panovisu/css/panovisu.css",media:"screen"}));
supportWebgl()||supportCanvas()||alert("Navigateur non support\u00e9");
